job:
  schedule: "@hourly"
  history:
    successful: 24
    failed: 3

# The secret must contain the environment variables mentioned in the readme.
# Additional environment variables can be supplied as name + value entries under env.extra.
env:
  storageFile: /srv/free-stuff-matrixbot/storage/storage.json
  secretName: free-stuff-matrixbot-secrets
  extra: []

# Enabling the PVC means that a PVC is created as part of the deployment.
# It's possible to leave PVC disabled, but set a name. This way no PVC will be created but is tried to be used.
# If no PVC is to be used a stateless in-memory volume will be created.
storage:
  volumeName: free-stuff-matrixbot-storage
  mountPath: /srv/free-stuff-matrixbot/storage
  pvc:
    enabled: false
    name: ""
    size: 1Gi
    storageClass: ""

image:
  repository: ghcr.io/siliciumpowered/free-stuff-matrixbot/free-stuff-matrixbot
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
