name: Containerize
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - ci/master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_SILICIUMPOWERED_PACKAGES_USERNAME }}
          password: ${{ secrets.GH_SILICIUMPOWERED_PACKAGES_PASSWORD }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/siliciumpowered/free-stuff-matrixbot/free-stuff-matrixbot:latest
